/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorRegistroUsuario;
import Implementacion.RegistroImp;
import Modelo.ModeloRegistroUsuario;

/**
 *
 * @author jhosu
 */
public class PanelRegistrarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrarUsuario
     */
    public PanelRegistrarUsuario() {
        initComponents();
        
        Modelo.ModeloRegistroUsuario modelo = new ModeloRegistroUsuario(this);
        Controlador.ControladorRegistroUsuario controlador = new ControladorRegistroUsuario(modelo);
        setControlador(controlador);
        RegistroImp implementacion = new RegistroImp();
        cmbTipoUsuario.setModel(implementacion.mostrarTiposUsuarios());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        letTituloProducto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContraseniaUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FondoRegistro = new javax.swing.JLabel();

        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letTituloProducto.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        letTituloProducto.setForeground(new java.awt.Color(255, 255, 255));
        letTituloProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letTituloProducto.setText("REGISTRO DE USUARIO");
        FondoPanel.add(letTituloProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 980, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE DE USUARIO");
        FondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FondoPanel.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 290, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA DE USUARIO");
        FondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        txtContraseniaUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtContraseniaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaUsuarioActionPerformed(evt);
            }
        });
        FondoPanel.add(txtContraseniaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 290, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DE USUARIO");
        FondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 20));

        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FondoPanel.add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 150, -1));

        btnRegistrar.setBackground(new java.awt.Color(48, 99, 99));
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR");

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        FondoPanel.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 130, 40));

        btnBorrar.setBackground(new java.awt.Color(48, 99, 99));
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BORRAR");

        javax.swing.GroupLayout btnBorrarLayout = new javax.swing.GroupLayout(btnBorrar);
        btnBorrar.setLayout(btnBorrarLayout);
        btnBorrarLayout.setHorizontalGroup(
            btnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBorrarLayout.setVerticalGroup(
            btnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        FondoPanel.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 130, 40));

        FondoRegistro.setBackground(new java.awt.Color(122, 167, 167));
        FondoRegistro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FondoRegistro.setForeground(new java.awt.Color(122, 167, 167));
        FondoRegistro.setOpaque(true);
        FondoPanel.add(FondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseniaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel FondoRegistro;
    public javax.swing.JPanel btnBorrar;
    public javax.swing.JPanel btnRegistrar;
    public javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel letTituloProducto;
    public javax.swing.JTextField txtContraseniaUsuario;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorRegistroUsuario controlador){
        btnRegistrar.addMouseListener(controlador);
        btnBorrar.addMouseListener(controlador);
        
    }





}
