/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.ControladorInventario;
import Modelo.ModeloInventario;



/**
 *
 * @author Cindy Ruano
 */
public class PanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();
        
        
        Modelo.ModeloInventario modelo = new ModeloInventario(this);
        Controlador.ControladorInventario controlador = new ControladorInventario(modelo);
        SetControlador(controlador);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        letTituloInventario = new javax.swing.JLabel();
        separadorDerecha = new javax.swing.JSeparator();
        separadorIzquierda = new javax.swing.JSeparator();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionIventario = new javax.swing.JTable();
        btnMostrarGestionInventario = new javax.swing.JPanel();
        letMostrarInventario = new javax.swing.JLabel();
        btnMostrarVentas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        letFondoInventario = new javax.swing.JLabel();

        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letTituloInventario.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        letTituloInventario.setForeground(new java.awt.Color(255, 255, 255));
        letTituloInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letTituloInventario.setText("INVENTARIO");
        fondoPanel.add(letTituloInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 70, 980, -1));

        separadorDerecha.setForeground(new java.awt.Color(255, 255, 255));
        separadorDerecha.setOpaque(true);
        fondoPanel.add(separadorDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 230, -1));

        separadorIzquierda.setForeground(new java.awt.Color(255, 255, 255));
        separadorIzquierda.setOpaque(true);
        fondoPanel.add(separadorIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 230, -1));

        panelTabla.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelTabla.setMinimumSize(new java.awt.Dimension(800, 370));
        panelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGestionIventario.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblGestionIventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGestionIventario);

        panelTabla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 370));

        fondoPanel.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 800, 370));

        btnMostrarGestionInventario.setBackground(new java.awt.Color(48, 99, 99));
        btnMostrarGestionInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letMostrarInventario.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        letMostrarInventario.setForeground(new java.awt.Color(255, 255, 255));
        letMostrarInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letMostrarInventario.setText("MOSTRAR REGISTROS INVENTARIO");
        btnMostrarGestionInventario.add(letMostrarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        fondoPanel.add(btnMostrarGestionInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 280, 40));

        btnMostrarVentas.setBackground(new java.awt.Color(48, 99, 99));
        btnMostrarVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MOSTRAR REGISTRO VENTAS");
        btnMostrarVentas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        fondoPanel.add(btnMostrarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 280, 40));

        letFondoInventario.setBackground(new java.awt.Color(122, 167, 167));
        letFondoInventario.setOpaque(true);
        fondoPanel.add(letFondoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnMostrarGestionInventario;
    public javax.swing.JPanel btnMostrarVentas;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel letFondoInventario;
    private javax.swing.JLabel letMostrarInventario;
    private javax.swing.JLabel letTituloInventario;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JSeparator separadorDerecha;
    private javax.swing.JSeparator separadorIzquierda;
    public javax.swing.JTable tblGestionIventario;
    // End of variables declaration//GEN-END:variables

    private void SetControlador(ControladorInventario controlador) {
        btnMostrarGestionInventario.addMouseListener(controlador);
        btnMostrarVentas.addMouseListener(controlador);
    }

  
}
