/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlador.ControladorVendedor;
import Modelo.ModeloVendedor;

/**
 *
 * @author Cindy Ruano
 */
public class VistaVendedor extends javax.swing.JFrame {

    /**
     * Creates new form VistaVendedor
     */
    public VistaVendedor() {
        initComponents();
        Modelo.ModeloVendedor modelo = new ModeloVendedor(this);
        Controlador.ControladorVendedor controlador = new ControladorVendedor(modelo);
        setControlador(controlador);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanelVendedor = new javax.swing.JPanel();
        letTituloVendedor = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btnVendedorVentas = new javax.swing.JPanel();
        letVendedorVentas = new javax.swing.JLabel();
        btnVendedorClientes = new javax.swing.JPanel();
        letVendedorClientes = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fondoVendedor = new javax.swing.JLabel();
        contenedor1 = new javax.swing.JPanel();
        contenedor2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoPanelVendedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letTituloVendedor.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        letTituloVendedor.setForeground(new java.awt.Color(255, 255, 255));
        letTituloVendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letTituloVendedor.setText("VENDEDOR");
        fondoPanelVendedor.add(letTituloVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, -1));

        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setOpaque(true);
        fondoPanelVendedor.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 190, -1));

        btnVendedorVentas.setBackground(new java.awt.Color(48, 99, 99));
        btnVendedorVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendedorVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letVendedorVentas.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        letVendedorVentas.setForeground(new java.awt.Color(255, 255, 255));
        letVendedorVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letVendedorVentas.setText("VENTAS");
        letVendedorVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendedorVentas.add(letVendedorVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        fondoPanelVendedor.add(btnVendedorVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 40));

        btnVendedorClientes.setBackground(new java.awt.Color(48, 99, 99));
        btnVendedorClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendedorClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letVendedorClientes.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        letVendedorClientes.setForeground(new java.awt.Color(255, 255, 255));
        letVendedorClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letVendedorClientes.setText("CLIENTES");
        btnVendedorClientes.add(letVendedorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        fondoPanelVendedor.add(btnVendedorClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 40));

        btnVolver.setBackground(new java.awt.Color(122, 167, 167));
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALIR");

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondoPanelVendedor.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 80, 40));

        fondoVendedor.setBackground(new java.awt.Color(48, 99, 99));
        fondoVendedor.setOpaque(true);
        fondoPanelVendedor.add(fondoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        contenedor1.setBackground(new java.awt.Color(122, 167, 167));

        javax.swing.GroupLayout contenedor1Layout = new javax.swing.GroupLayout(contenedor1);
        contenedor1.setLayout(contenedor1Layout);
        contenedor1Layout.setHorizontalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        contenedor1Layout.setVerticalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        fondoPanelVendedor.add(contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 980, 720));

        contenedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondoPanelVendedor.add(contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnVendedorClientes;
    public javax.swing.JPanel btnVendedorVentas;
    public javax.swing.JPanel btnVolver;
    public javax.swing.JPanel contenedor1;
    private javax.swing.JPanel contenedor2;
    private javax.swing.JPanel fondoPanelVendedor;
    private javax.swing.JLabel fondoVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letTituloVendedor;
    private javax.swing.JLabel letVendedorClientes;
    private javax.swing.JLabel letVendedorVentas;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
    public void setControlador(ControladorVendedor controlador){
        this.addWindowListener(controlador);
        btnVendedorVentas.addMouseListener(controlador);
        btnVendedorClientes.addMouseListener(controlador);
        btnVolver.addMouseListener(controlador);
    }
}
